services:
  express:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: "postgres:15.4-bullseye"
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgresql: {}

